#!/bin/bash
# Program to get the current Muslim prayer time using an API

# Get the current date in the required format (dd-mm-yyyy)
current_date=$(date +%d-%m-%Y)

# API URL using the current date variable
api_url="http://api.aladhan.com/v1/timingsByCity/$current_date?city=Bloomington&state=Minnesota&country=United+States"

# Get the data from the API
prayer_data=$(curl -s "$api_url")

# Function to convert 24-hour time to 12-hour time
convert_to_12_hour() {
    timestamp="$1"
    date -d "@$timestamp" '+%I:%M %p'
}

# Parse the data from JSON
fajr_unix_time=$(echo "$prayer_data" | jq -r '.data.timings.Fajr' | date -f - +%s)
dhuhur_unix_time=$(echo "$prayer_data" | jq -r '.data.timings.Dhuhr' | date -f - +%s)
asr_unix_time=$(echo "$prayer_data" | jq -r '.data.timings.Asr' | date -f - +%s)
maghrib_unix_time=$(echo "$prayer_data" | jq -r '.data.timings.Maghrib' | date -f - +%s)
isha_unix_time=$(echo "$prayer_data" | jq -r '.data.timings.Isha' | date -f - +%s)

# Get the current Unix timestamp
current_unix_time=$(date +%s)

# Check what time it is closest to and display the next upcoming prayer time in 12-hour format
#if [[ $current_unix_time -lt $fajr_unix_time ]]; then
#    echo "  Fajr: $(convert_to_12_hour $fajr_unix_time)"
#elif [[ $current_unix_time -lt $dhuhur_unix_time ]]; then
#    echo "  Duhur: $(convert_to_12_hour $dhuhur_unix_time)"
#elif [[ $current_unix_time -lt $asr_unix_time ]]; then
#    echo "  Asr: $(convert_to_12_hour $asr_unix_time)"
#elif [[ $current_unix_time -lt $maghrib_unix_time ]]; then
#    echo "  Maghrib: $(convert_to_12_hour $maghrib_unix_time)"
#elif [[ $current_unix_time -lt $isha_unix_time ]]; then
#    echo "  Isha: $(convert_to_12_hour $isha_unix_time)"
#else
    # If all prayers have passed, show the next day's Fajr
#    fajr_tomorrow=$(echo $prayer_data | jq -r ".data.date.gregorian.date" | awk -F'-' '{print $3"-"$2"-"$1+1}')
#    fajr_tomorrow=$(curl -s "http://api.aladhan.com/v1/timingsByCity/$fajr_tomorrow?city=Bloomington&state=Minnesota&country=United+States" | jq -r ".data.timings.Fajr" | date -f - +%s)
#    echo "  󱠧 Fajr: $(convert_to_12_hour $fajr_tomorrow)"
#fi
#
if [[ $current_unix_time -lt $fajr_unix_time ]]; then
    echo "  󱠧 $(convert_to_12_hour $fajr_unix_time)"
elif [[ $current_unix_time -lt $dhuhur_unix_time ]]; then
    echo "  󱠧  $(convert_to_12_hour $dhuhur_unix_time)"
elif [[ $current_unix_time -lt $asr_unix_time ]]; then
    echo "  󱠧  $(convert_to_12_hour $asr_unix_time)"
elif [[ $current_unix_time -lt $maghrib_unix_time ]]; then
    echo "  󱠧  $(convert_to_12_hour $maghrib_unix_time)"
elif [[ $current_unix_time -lt $isha_unix_time ]]; then
    echo "  󱠧  $(convert_to_12_hour $isha_unix_time)"
else
    # If all prayers have passed, show the next day's Fajr
    fajr_tomorrow=$(echo $prayer_data | jq -r ".data.date.gregorian.date" | awk -F'-' '{print $3"-"$2"-"$1+1}')
    fajr_tomorrow=$(curl -s "http://api.aladhan.com/v1/timingsByCity/$fajr_tomorrow?city=Bloomington&state=Minnesota&country=United+States" | jq -r ".data.timings.Fajr" | date -f - +%s)
    echo "  󱠧 Fajr: $(convert_to_12_hour $fajr_tomorrow)"
fi
