#!/bin/bash

#vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2}' | sed 's/0//g' | tr '.' ' ')"


#echo $vol


# Prints the current volume or 󰖁 if muted.

case $BLOCK_BUTTON in
  1) setsid -f "$TERMINAL" -e pulsemixer ;;
  2) wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle ;;
  4) wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%+ ;;
  5) wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%- ;;
  3) notify-send " Volume module" "\- Shows volume , 󰖁 if muted.
- Middle click to mute.
- Scroll to change." ;;
  6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

# Get volume information once and store it in a variable
vol_info="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"

# If muted, print 󰖁 and exit.
if echo "$vol_info" | grep -q '\[MUTED\]'; then
  echo 󰖁
  exit
fi

# Extract the volume percentage
vol_percentage=$(echo "$vol_info" | awk '{print $2}' | sed 's/0//g' | tr -d '.')

# Determine the icon based on volume percentage
case $vol_percentage in
  [1-29]) icon=" " ;;
  [30-69]) icon=" " ;;
  *) icon="" ;;
esac

echo "$icon $vol_percentage%"
