[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\v/home/termi)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\n\0\0\0'\0\0\x4\x15\0\0\x4-\0\0\0\n\0\0\0'\0\0\x4\x1f\0\0\x4-\0\0\0\0\0\0\0\0\a\x80\0\0\0\n\0\0\0'\0\0\x4\x1f\0\0\x4-)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(600 0)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[OpenDialog]
advanced=false
netMRL=https://dood.wf/e/5vv5yvkmwi7u
size=@Size(526 405)

[RecentsMRL]
list=https://dood.wf/e/5vv5yvkmwi7u, https://embedsito.com/v/j-j1pcdlr4m43l5, file:///home/termi/Downloads/%5BYT2mp3.info%5D%20-%20%E2%96%B6%20PHONK%20WORKOUT%20MIX_%20_%20GYM_%20playlist%20%5BVol.1%5D%20%28320kbps%29.mp3, file:///home/termi/.myconfig/../Downloads/%5BYT2mp3.info%5D%20-%20%E2%96%B6%20PHONK%20WORKOUT%20MIX_%20_%20GYM_%20playlist%20%5BVol.1%5D%20%28320kbps%29.mp3, file:///home/termi/Downloads/did%20you%20just%20say%20classical%20music%20is%20boring_%21%20%28playlist%29.mp3
times=0, 0, 0, 0, 555292
