#! /bin/sh
#just checking
#nitrogen --set-zoom-fill --random ~/wallpapers
pgrep -x sxhkd > /dev/null || sxhkd &


feh --bg-fill -z ~/wallpapers3/wallhaven-85852j.jpg
eww open bspwm-bar --config /home/termai/.config/eww/bar_bspwm/.
xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width				2
bspc config window_gap					5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config ignore_ewmh_struts          true
bspc config top_padding                 40


bspc config focused_border_color "#808bd9"
bspc config normal_border_color "#23262b"
#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a brave desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
