#!/bin/bash

batt=$(cat /sys/class/power_supply/BAT1/capacity)

if [[ $batt -le 5 ]]
then
  echo " $batt%"
elif [[ $batt -le 20 ]]
then
  echo " $batt%"
elif [[ $batt -le 35 ]]
then
  echo " $batt%"
elif [[ $batt -le 60 ]]
then
  echo " $batt%"
else
  echo " $batt%"
fi
