#!/bin/bash

# Get the volume percentage using amixer
vol=$(amixer -D pulse sget Master | grep -oE '[0-9]{1,3}%' | head -n 1 | sed 's/%//')

# Set volume icon based on volume percentage
if [[ $vol -lt 15 ]]; then
    vol_icon="🔈"
elif [[ $vol -lt 50 ]]; then
    vol_icon="🔉"
else
    vol_icon="🔊"
fi

echo " $vol_icon $vol% "

#xsetroot -name "$vol | $"

